name: Check license header

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Check license headers
      uses: apache/skywalking-eyes@v0.3.0
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          config: .github/licenserc.yml
          mode: fix

    - name: Create pull request
      if: github.event_name != 'pull_request'
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: "chore: add license header(s)"
        title: "chore: add license header(s)"
        body: Add missing license header(s) in source and test code.
        branch: add-license

    - name: Commit licensed files
      if: github.event_name == 'pull_request'
      uses: EndBug/add-and-commit@v8.0.2
      with:
        author_name: GitHub
        author_email: noreply@github.com
        message: "chore: add license header(s)"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
