name: Check license header

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Check License Header
      uses: apache/skywalking-eyes@v0.3.0
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          config: .github/licenserc.yml
          mode: fix

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: "chore: add license header(s)"
        title: "chore: add license header(s)"
        body: Add missing license header(s) in source and test code.
        branch: add-license


on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Check License Header
      uses: apache/skywalking-eyes@v0.3.0
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          config: .github/licenserc.yml
          mode: fix

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: "chore: add license header(s)"
        title: "chore: add license header(s)"
        body: Add missing license header(s) in source and test code.
        branch: add-license
